### ISSUE TITLE
vlxml is missing in dependences

### ISSUE THREAD

**Issue by samvy** [cwaldbieser/jhub_cas_authenticator#1]
Dear Cwaldbieser,
After instalation : 'ModuleNotFoundError: No module named 'lxml''
Regards,

**Comment by cwaldbieser** [comment]
I've updated this in commit 983c1b03e58c374806ef57f37330d9f73666a8d4.
I'm waiting to test all your issues before I cut a new version and update PyPi, though.

**Comment by cwaldbieser** [comment]
This is handled in the new release.
