### ISSUE TITLE
CASLocalAuthenticator does not create the users at login

### ISSUE THREAD

**Issue by miguelmarco** [cwaldbieser/jhub_cas_authenticator#13]
I have installed a test server that uses CASLocalAuthenticator, with c.CASLocalAuthenticator.create_system_users = True

However, when a user correctly authenticates, it is not created in the system; and a get a 'getpwham(): name not found' error.

When I restart the jupyterhub server, then the users that did log before get created in the system, and then they can normally use the system, but what would make sense is to have them created at login time.

**Comment by cwaldbieser** [comment]
Could you include your JupterHub config without any secrets like passwords so I can try it out and see if I can tell what is going on?

**Comment by miguelmarco** [comment]
The only non commented lines are the following:

```
c.JupyterHub.authenticator_class = 'jhub_cas_authenticator.cas_auth.CASLocalAuthenticator'
c.CASLocalAuthenticator.cas_login_url = 'https://sso.unizar.es:8443/mail/login'
c.CASLocalAuthenticator.cas_logout_url = 'https://sso.unizar.es:8443/mail/logout'
c.CASLocalAuthenticator.cas_service_url = 'http://localhost:8000/login'
c.CASLocalAuthenticator.cas_client_ca_certs = '/etc/ssl/certs/DigiCert_Assured_ID_Root_CA.pem'
c.CASLocalAuthenticator.cas_service_validate_url = 'https://sso.unizar.es:8443/mail/serviceValidate'
c.CASLocalAuthenticator.cas_required_attribs = set()
c.CASLocalAuthenticator.create_system_users = True
c.Spawner.cmd = ['jupyter-labhub']
c.Spawner.default_url = '/lab'
```

**Comment by miguelmarco** [comment]
I am finding this problem again. It did work for a while, but after an update it stoped creating users. One change I introduced was to put jupyterhub behind a nginx proxy, but I would be surprised if that were related.

It seems that the add_user method of LocalAuthenticator is not called after a succesful first login (but it is called on startup, so if I restart the jupyterhub service, it creates as system user for each users that had loged in, but couldn't be spawned because their system user did not exist.

**Comment by garymol** [comment]
I can second this reported issue.   Upon first login, the local accounts are not created, but a restart of the server will sync the account to the local system.

**Comment by cwaldbieser** [comment]
Looking at the current Jupyterhub code base, it looks to me like the LocalAuthenticator requires the `authenticate()` method to be called for system users to be created on login.  That is a problem for the CAS authenticator, because authentication happens externally.

I think the [`pre_spawn_start()` method](https://jupyterhub.readthedocs.io/en/latest/api/auth.html#jupyterhub.auth.Authenticator.pre_spawn_start) might be able to be used to create the user somehow, but I'm not sure what the best way to do that might be. 

It might make sense to inherit from `PAMAuthenticator`, instead, and then call its user-creating machinery during the above hook.  I'll have to do some research.

**Comment by louvois** [comment]
Hi,

I am using CASLocalAuthenticator, and it does not create users at login.  Have any one found a solution for this issue ? Thanks

**Comment by cwaldbieser** [comment]
I had posted an issue on the Jupyter Google group:

https://groups.google.com/forum/#!topic/jupyter/Fc7G_jGEJX0

So far, I haven't gotten any response.  I may try a polite bump on that thread.

I'm happy to accept any PRs if anyone has any ideas.  I just haven't had the time to experiment with this.

**Comment by cwaldbieser** [comment]
It might also be possible to use the Jupyterhub REST API to create users on successful authentication: https://jupyterhub.readthedocs.io/en/stable/_static/rest-api/index.html#path--users--name-

**Comment by cwaldbieser** [comment]
I've pushed a change to master.  My tests show that this corrects the issue, but I'd like to here from others that this resolves the issue before I close it.  If someone who reported this could test, that would be great.

**Comment by louvois** [comment]
Hello,

Excellent work ! It works for me. Thank you very much.

regards,
P.  Louvois

**Comment by cwaldbieser** [comment]
Excellent!  I will push out a release, and then close this ticket.

**Comment by cwaldbieser** [comment]
Release can be found here: https://pypi.org/project/jhub-cas-authenticator/#history
