### ISSUE TITLE
Current release broken, fix in pull request #16 corrects it

### ISSUE THREAD

**Issue by liffiton** [cwaldbieser/jhub_cas_authenticator#17]
The current PyPI release of jhub_cas_authenticator causes a server error on login, while installing directly from the github repository works correctly.  This is with Jupyterhub 1.1.0.

**Comment by cwaldbieser** [comment]
@liffiton - I don't see any PRs under my pull request tab for this repo-- did you submit one?

**Comment by liffiton** [comment]
Sorry.  To be clearer, #16 has already been merged.  It just needs a release to PyPI, I think.

**Comment by cwaldbieser** [comment]
Sorry, I didn't pick up on that!  I've made a new release.

**Comment by liffiton** [comment]
No worries.  Thanks!
