### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by thinkingmik** [cwaldbieser/jhub_cas_authenticator#18]
Hi, 

how can I configure `jupyterhub` for see debug logs? I saw that in the code [cas_auth.py](https://github.com/cwaldbieser/jhub_cas_authenticator/blob/master/jhub_cas_authenticator/cas_auth.py#L46) there are some usefull  logs.

Thanks.

**Comment by cwaldbieser** [comment]
Take a look at [this jupyterhub config file](https://github.com/cwaldbieser/vagrant_jhub_cas_test_env/blob/master/srv/jupyterhub/jupyterhub_config.py), line 6.

**Comment by thinkingmik** [comment]
Thank you very much
