### ISSUE TITLE
Does jhub_cas_authenticator plugin support django-cas?

### ISSUE THREAD

**Issue by ghost** [cwaldbieser/jhub_cas_authenticator#19]
Hello cwaldbieser,

First of all thank you for this awesome plugin, I'd like to report an issue on our below jupyterhub-deploy-docker and  django-cas-server configuration. 

TLDR; after trying to login jupyterhub via django-cas using jhub_cas_authenticator which has been configured to retrieve username and password data from a postgresql database; cas_auth function always return 401 Unauthorized error and does not let the dockerspawner create a notebook container for jupyterhub.

Here's the version information :

Jupyterhub (v0.9.6) https://github.com/jupyterhub/jupyterhub-deploy-docker
jhub_cas_authenticator (installed via pip inside the jupyterhub docker container the latest version v1.0.2)
django-cas https://github.com/nitmir/django-cas-server (which provides CAS 3.0 implementation)

So after we setup django-cas on CAS domain and configured the jupyterhub_config.py file for the required endpoints when we navigate to our jupyterhub instance which is running on https://jupyter.ep3data.com/hub/login, it succesfully navigates us to the cas login page but after trying to login with a user defined in postgresql database source it always return 401 unauthorized errors. I will provide the debug logs from jupyterhub as well.

I have the following jupyterhub_config.py file for your reference :

```
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# Configuration file for JupyterHub
import os

c = get_config()

c.JupyterHub.admin_access = True
c.Spawner.default_url = '/lab'

c.JupyterHub.log_level = 'DEBUG'
c.Spawner.debug = True

# We rely on environment variables to configure JupyterHub so that we
# avoid having to rebuild the JupyterHub container every time we change a
# configuration parameter.

# Spawn single-user servers as Docker containers
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
# Spawn containers from this image
c.DockerSpawner.container_image = os.environ['DOCKER_NOTEBOOK_IMAGE']
# JupyterHub requires a single-user instance of the Notebook server, so we
# default to using the `start-singleuser.sh` script included in the
# jupyter/docker-stacks *-notebook images as the Docker run command when
# spawning containers.  Optionally, you can override the Docker run command
# using the DOCKER_SPAWN_CMD environment variable.
spawn_cmd = os.environ.get('DOCKER_SPAWN_CMD', "start-singleuser.sh")
c.DockerSpawner.extra_create_kwargs.update({ 'command': spawn_cmd })
# Connect containers to this Docker network
network_name = os.environ['DOCKER_NETWORK_NAME']
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.network_name = network_name
# Pass the network name as argument to spawned containers
c.DockerSpawner.extra_host_config = { 'network_mode': network_name }
# Explicitly set notebook directory because we'll be mounting a host volume to
# it.  Most jupyter/docker-stacks *-notebook images run the Notebook server as
# user `jovyan`, and set the notebook directory to `/home/jovyan/work`.
# We follow the same convention.
notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan/work'
c.DockerSpawner.notebook_dir = notebook_dir
# Mount the real user's Docker volume on the host to the notebook user's
# notebook directory in the container
c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir }
# volume_driver is no longer a keyword argument to create_container()
# c.DockerSpawner.extra_create_kwargs.update({ 'volume_driver': 'local' })
# Remove containers once they are stopped
c.DockerSpawner.remove_containers = True
# For debugging arguments passed to spawned containers
c.DockerSpawner.debug = True

# User containers will access hub by container name on the Docker network
c.JupyterHub.hub_ip = 'jupyterhub'
c.JupyterHub.hub_port = 8080

# TLS config
c.JupyterHub.port = 443
c.JupyterHub.ssl_key = os.environ['SSL_KEY']
c.JupyterHub.ssl_cert = os.environ['SSL_CERT']

# Authenticate users with GitHub OAuth
# c.JupyterHub.authenticator_class = 'oauthenticator.GitHubOAuthenticator'
# c.GitHubOAuthenticator.oauth_callback_url = os.environ['OAUTH_CALLBACK_URL']

# c.JupyterHub.authenticator_class = 'nativeauthenticator.NativeAuthenticator'
# c.NativeAuthenticator.open_signup = True


c.JupyterHub.authenticator_class = 'jhub_cas_authenticator.cas_auth.CASLocalAuthenticator'
c.CASLocalAuthenticator.cas_login_url = 'https://cas.ep3data.com/cas/login'
c.CASLocalAuthenticator.cas_logout_url = 'https://cas.ep3data.com/cas/logout'

# c.Authenticator.admin_users = {'admin','test','aydintd'}
# The service URL the CAS server will redirect the browser back to on successful authentication.
# If not set, this is set to the same URL the request comes in on.  This will work fine for
# simple deployments, but deployments behind a proxy or load banalncer will likely need to
# be adjusted so the CAS service redirects back to the *real* login URL for your Jupyterhub.
c.CASLocalAuthenticator.cas_service_url = 'https://jupyter.ep3data.com/hub/login'

#c.CASLocalAuthenticator.cas_client_ca_certs = '/path/to/ca_certs.pem'
c.CASLocalAuthenticator.cas_service_validate_url = 'https://cas.ep3data.com/cas/p3/serviceValidate'
c.CASLocalAuthenticator.cas_required_attribs = {('memberOf', 'jupyterhub_users')}
c.CASLocalAuthenticator.whitelist = {'admin','test','aydintd','peterb','chirag'}
c.Authenticator.admin_users = {'admin','test'}
# c.CASLocalAuthenticator.create_system_users = True

# Persist hub data on volume mounted inside container
data_dir = os.environ.get('DATA_VOLUME_CONTAINER', '/data')

c.JupyterHub.cookie_secret_file = os.path.join(data_dir,
    'jupyterhub_cookie_secret')

c.JupyterHub.db_url = 'postgresql://postgres:{password}@{host}/{db}'.format(
    host=os.environ['POSTGRES_HOST'],
    password=os.environ['POSTGRES_PASSWORD'],
    db=os.environ['POSTGRES_DB'],
)
```

What I see in the jupyterhub debug logs during the login attempt is :

```
[I 2020-08-27 22:34:41.037 JupyterHub log:158] 302 GET /hub -> /hub/ (@184.69.65.66) 0.62ms
[I 2020-08-27 22:34:41.074 JupyterHub log:158] 302 GET /hub/ -> /hub/login (@184.69.65.66) 1.08ms
[D 2020-08-27 22:34:41.107 JupyterHub cas_auth:49] Has service ticket? False
[D 2020-08-27 22:34:41.107 JupyterHub cas_auth:57] Redirecting to CAS to get service ticket: https://cas.ep3data.com/cas/login?service=https%3A%2F%2Fjupyter.ep3data.com%2Fhub%2Flogin
[I 2020-08-27 22:34:41.108 JupyterHub log:158] 302 GET /hub/login -> https://cas.ep3data.com/cas/login?service=https%3A%2F%2Fjupyter.ep3data.com%2Fhub%2Flogin (@184.69.65.66) 1.19ms
[D 2020-08-27 22:34:55.909 JupyterHub cas_auth:49] Has service ticket? True
[D 2020-08-27 22:34:55.909 JupyterHub cas_auth:62] Validating service ticket ST-B49MY3E...
[D 2020-08-27 22:34:55.910 JupyterHub cas_auth:122] Validate URL: https://cas.ep3data.com/cas/p3/serviceValidate?service=https%3A%2F%2Fjupyter.ep3data.com%2Fhub%2Flogin&ticket=ST-B49MY3EmJEYYYe3yVvuKXaSYFurmHUBTW6oo3TdF7hLj5bBpJFRtoiKOJPh5A
[D 2020-08-27 22:35:15.911 JupyterHub cas_auth:130] Response was unsuccessful: None
[D 2020-08-27 22:35:15.911 JupyterHub base:890] No template for 401
[W 2020-08-27 22:35:15.912 JupyterHub log:158] 401 GET /hub/login?ticket=ST-B49MY3EmJEYYYe3yVvuKXaSYFurmHUBTW6oo3TdF7hLj5bBpJFRtoiKOJPh5A (@184.69.65.66) 20003.36ms
[D 2020-08-27 22:35:16.157 JupyterHub log:158] 304 GET /favicon.ico (@184.69.65.66) 1.06ms
```

What I see when I clicked on the ServiceValidation URL generated for this login I can see that the user authentication is actually succesful on the django-cas side before it expires :

```
<cas:serviceResponse xmlns:cas="http://www.yale.edu/tp/cas">
<cas:authenticationSuccess>
<cas:user>test</cas:user>
<cas:attributes>
<cas:authenticationDate>2020-08-27T22:34:55+00:00</cas:authenticationDate>
<cas:longTermAuthenticationRequestTokenUsed>false</cas:longTermAuthenticationRequestTokenUsed>
<cas:isFromNewLogin>true</cas:isFromNewLogin>
</cas:attributes>
<cas:attribute name="authenticationDate" value="2020-08-27T22:34:55+00:00"/>
<cas:attribute name="longTermAuthenticationRequestTokenUsed" value="false"/>
<cas:attribute name="isFromNewLogin" value="true"/>
</cas:authenticationSuccess>
</cas:serviceResponse>

```
So even it returns a successful authentication code, for some reason cas_auth function still returns .[.. cas_auth:130] Response was unsuccessful: None so that makes me think maybe the plugin does not support django-cas at all.

If you can share your insights on this issue here I'd be very appreciated and if we can make this work on our end I can provide a technical documentation on how to hookup jupyterhub + django-cas by using this plugin for the community!

Please let us know your thoughts!

**Comment by cwaldbieser** [comment]
The issue seems to be in this section of code:
`        try:
            response = await http_client.fetch(
                cas_validate_url,
                method="GET",
                ca_certs=self.authenticator.cas_client_ca_certs)
            app_log.debug("Response was successful: {0}".format(response))
        except HTTPError as ex:
            app_log.debug("Response was unsuccessful: {0}".format(response))
            return (False, None, None)
`
This means that JupyterHub (the CAS client) received the service ticket from Django CAS (the CAS server) via the user's browser.  It tried to validate the ticket, but an HTTP error was thrown.  Unfortunately, the error logging should probably print out the exception (`ex`) rather than the response.  Without knowing what the HTTP error is, it is hard to diagnose.  If you could change the debug statement to print out the exception, that might help us determine what is going on.

**Comment by ghost** [comment]
You were right thank you very much for the advice :-)

I modified the cas_auth.py like following and reinstalled the plugin via pip install . inside the plugin source code:

`except HTTPError as ex:`
        `app_log.debug("Response was unsuccessful: {0} and {1}".format(response,ex))`

and I was getting this:

`Aug 28 00:14:28 jupyterhub[441490]: [D 2020-08-28 00:14:28.395 JupyterHub cas_auth:130] Response was unsuccessful: None and Timeout while connecting`

figured out it's a DNS issue from our jupyterhub container when it tries to resolve the domain address of our CAS server, where I fixed the issue was adding extra_hosts: to my jupyterhub deployment container in docker-compose.yml file so after rebuilding my setup, the users started to authenticate through the django-cas server smoothly. It's always DNS. 

ticket can be closed.
