### ISSUE TITLE
Logout not implemented

### ISSUE THREAD

**Issue by liffiton** [cwaldbieser/jhub_cas_authenticator#6]
When pressing a logout button in Jupyterhub, it logs out of Jupyterhub and redirects to the login url.  The login URL redirects to the CAS login url, and if it hasn't been too long, that automatically redirects back to the Jupyterhub service and logs you in.  So pressing "logout" results in some redirects that end up back at the same page, still logged in.

I could work on implementing logout and submit a pull request if it would help.

**Comment by cwaldbieser** [comment]
I've committed this PR.  I'll leave the issue open until I push a release to PyPI.

**Comment by romosch** [comment]
Any news on this?

**Comment by cwaldbieser** [comment]
Thanks for reminding me.  I'll try to push something up to PyPI this week or next week.  Feel free to remind me if I haven't done anything by June 13, 2018.  I sometimes lose track.

**Comment by cwaldbieser** [comment]
OK, this has been release in version 0.2.0.
https://pypi.org/project/jhub-cas-authenticator/0.2.0/
