### ISSUE TITLE
jupyterhub can't correctly recognized User

### ISSUE THREAD

**Issue by moskiGithub** [cwaldbieser/jhub_cas_authenticator#9]
I use k8s deployer jupytehub and cas, But I login it. Jupyterhub return 401 error
jupyterhub and cas configure:
>>>
c.JupyterHub.authenticator_class = 'jhub_cas_authenticator.cas_auth.CASAuthenticator' c.CASAuthenticator.cas_login_url= https://xlab.cmbchina.biz:8443/login
c.CASAuthenticator.cas_service_validate_url= http://10.105.254.73:8080/cas/p3/serviceValidate 
c.CASAuthenticator.cas_service_url=https://xlab.cmbchina.biz:8443/jupyterhub/login
c.CASAuthenticator.cas_required_attribs = {('memberOf', '+ jupyterhub_users')}

**Comment by cwaldbieser** [comment]
I probably don't have enough information to tell you exactly what is wrong, but I can take an educated guess.

The CAS login URL and the CAS `/serviceValidate` URL are typically both served from this domain, and they typically share a common root.  So:

Typical:
* https://xlab.cmbchina.biz:8443/cas/login
* https://xlab.cmbchina.biz:8443/cas/p3/serviceValidate
Typical:
* https://xlab.cmbchina.biz:8443/login
* https://xlab.cmbchina.biz:8443/p3/serviceValidate
Possible, but not typical, usually requires special configuration:
* https://xlab.cmbchina.biz:8443/login
* https://xlab.cmbchina.biz:8443/cas/p3/serviceValidate

So I'd guess that the 404 error is that either the CAS login URL or the CAS `/serviceValidate` URL is not being found.  (You weren't clear which URL triggered the 404).

Does that help?

**Comment by cwaldbieser** [comment]
Did you ever determine what the issue was?  If I don't hear back in a couple of weeks, I'll just close the ticket.
